# Generated by Django 4.2.3 on 2025-04-18 11:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_weight',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Total weight of items in cart in kilograms', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Weight in kilograms', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
            preserve_default=False,
        ),
    ]
