# Generated by Django 4.2.3 on 2025-05-04 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0003_cart_total_weight_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='fraud_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='fraud_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CartWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_weight', models.DecimalField(decimal_places=3, help_text='Actual weight measured from the scale in kilograms', max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='cart_app.cart')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
