# Generated by Django 4.2.3 on 2025-05-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0006_cart_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user_cart',
        ),
    ]
